### PR TITLE
Fix Unity 6000.5 editor compile error in AppleBuildProfileEditor (CS0619)

### PR DESCRIPTION
**Pull request by oscarmakala**
## Problem

Unity 6000.5 completes the InstanceID → `EntityId` migration and marks `AssetDatabase.GetAssetPath(int instanceID)` as **error-level obsolete (CS0619, not suppressible)**. `AppleBuildProfileEditor.cs` calls it via `objectReferenceValue.GetInstanceID()` in two places (the default Info.plist and default entitlements pickers), so **Apple.Core fails to compile in the editor on Unity 6000.5+**, which blocks every plug-in that depends on it (GameKit, etc.).

```
error CS0619: 'AssetDatabase.GetAssetPath(int)' is obsolete
```

## Fix

Use the `AssetDatabase.GetAssetPath(UnityEngine.Object)` overload directly with `objectReferenceValue` — it has existed since Unity 5, so the change is compatible with all Unity versions the plug-ins support; no version defines needed.

```csharp
- string filePath = AssetDatabase.GetAssetPath(_serializedDefaultInfoPlist.objectReferenceValue.GetInstanceID());
+ string filePath = AssetDatabase.GetAssetPath(_serializedDefaultInfoPlist.objectReferenceValue);
```

(and the same for `_serializedDefaultEntitlements`.)

## Testing

- Compiles clean on Unity 6000.5.9f1 (editor recompile, zero errors) and behaves identically: the returned asset paths are unchanged.
- In production use in a shipping project on 6000.5 (Apple.Core 3.2.0 + GameKit 4.0.1, rebuilt with this patch): editor, iOS device builds, and Game Center flows all working.

Both `main` and `27-beta` currently carry the affected code.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by ryzngard** [comment]
Fixed in #104
