### PR TITLE
Fix Unity 6.5 build error in AppleBuildProfileEditor (CS0619)

### PR DESCRIPTION
**Pull request by mateuszjanczewski**
### Problem

`Apple.Core` does not compile on **Unity 6.5 (6000.5)**.

Unity 6.5 changes `Object.GetInstanceID()` to return `EntityId`, and makes the
`EntityId` → `int` implicit conversion **obsolete as an error** rather than a warning:

```
error CS0619: 'EntityId.implicit operator int(EntityId)' is obsolete:
'Use EntityId explicitly instead of int'
```

`AppleBuildProfileEditor.cs` calls `AssetDatabase.GetAssetPath(int)` in two places, so
the editor assembly fails to build and `python3 build.py` cannot produce the plug-in
packages on 6.5.

Both sites are still present on `main` as of 4b2455f:

- `plug-ins/Apple.Core/Apple.Core_Unity/Assets/Apple.Core/Editor/AppleBuildProfileEditor.cs:183`
- `plug-ins/Apple.Core/Apple.Core_Unity/Assets/Apple.Core/Editor/AppleBuildProfileEditor.cs:235`

### Fix

Both call sites already hold the `Object` itself, so they can use the
`AssetDatabase.GetAssetPath(Object)` overload directly:

```diff
-string filePath = AssetDatabase.GetAssetPath(_serializedDefaultInfoPlist.objectReferenceValue.GetInstanceID());
+string filePath = AssetDatabase.GetAssetPath(_serializedDefaultInfoPlist.objectReferenceValue);
```

This is equivalent — `GetAssetPath(int)` resolved the instance id back to the same
object — and it is **not conditional on 6.5**: the `Object` overload has existed for a
long time, so this compiles on older Unity versions too and needs no version guard.

### Testing

Applied against Unity 6000.5.9f1 in a project that consumes
`com.apple.unityplugin.core` and `com.apple.unityplugin.gamekit` via `build.py`
packages. With the change, `Apple.Core` compiles, `build.py` produces the packages,
and the consuming project builds for iOS and macOS. Without it, the editor assembly
fails to compile on 6.5.

The change is confined to two editor-only inspector call sites and does not touch
runtime plug-in behaviour.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by ryzngard** [comment]
Thank you for contributing. This has been resolved with #107
